name: fast_food
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # localization
  intl: ^0.18.1
  flutter_cache_manager: ^3.3.0
  # state management
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  # networking
  dio: ^5.0.1
  # conditional builder for make some conditions
  conditional_builder_null_safety: ^0.0.6
  # load image for one time
  cached_network_image: ^3.3.0
  # indicator for page view
  smooth_page_indicator: ^1.1.0
  # to change fonts
  google_fonts: ^6.1.0
  # loading indicator
  loading_indicator: ^3.1.0
  # to launch links
  url_launcher: ^6.1.11
  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # responsive
  flutter_screenutil: ^5.8.4
  #
  equatable: ^2.0.5
  custom_navigation_bar: ^0.8.2
  flutter_iconly: ^1.0.2
  flutter_svg: ^2.0.7
  iconly: ^1.0.1
  gap: ^3.0.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  icons_plus: ^5.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  toastification: ^1.2.0
  carousel_slider: ^4.2.1
  # for animation
  flutter_slidable: ^3.0.1
  lottie: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/on_boarding/
    - assets/images/home/

